version: "3"
services:
   nginx:
     image: nginx:latest
     container_name: reverse_proxy
     depends_on:
       - web_01
       - web_02
       - web_03
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
     ports:
       - 5001:5000
   web_01:
     image: web_service
     container_name: web_01
     environment: 
       CUST_MESSAGE: "This is web_01, Hello!"
     build: 
       context: ./web_service 
     expose:
       - "5000"
   web_02:
     image: web_service
     container_name: web_02

     # The below is commented out so the web_02 server when hit will display the default welcome message
     #environment: 
     #  CUST_MESSAGE: "This is web_02, Hello!"

     build: 
       context: ./web_service 
     expose:
       - "5000"
   web_03:
     image: web_service
     container_name: web_03
     environment: 
       CUST_MESSAGE: "This is web_03, Hello!"
     build: 
       context: ./web_service 
     expose:
      - "5000"
